// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SelectController from "./select_controller.js"
import TrackerController from "./tracker_controller.js"
import MapLoaderController from "./map_loader_controller.js"
import CheckInController from "./check_in_controller.js"

application.register("select", SelectController)
application.register("tracker", TrackerController)
application.register("map-loader", MapLoaderController)
application.register("check-in", CheckInController)
