// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckInController from "./check_in_controller.js"
import CloudflareTurnstile from "./cloudflare_turnstile_controller.js"
import CollectionsFilterController from "./collections_filter_controller.js"
import HomeFiltersController from "./home_filters_controller.js"
import MapLoaderController from "./map_loader_controller.js"
import MapsController from "./maps_controller.js"
import PwaInstallController from "./pwa_install_controller.js"
import SelectController from "./select_controller.js"
import TrackerController from "./tracker_controller.js"

application.register("check-in", CheckInController)
application.register("cloudflare-turnstile", CloudflareTurnstile)
application.register("collections-filter", CollectionsFilterController)
application.register("home-filters", HomeFiltersController)
application.register("map-loader", MapLoaderController)
application.register("maps", MapsController)
application.register("pwa-install", PwaInstallController)
application.register("select", SelectController)
application.register("tracker", TrackerController)
