service: petakopi

image: amree/petakopi.my

deploy_timeout: 60

servers:
  web:
    hosts:
      - petakopi-my-v3
    labels:
      traefik.http.routers.petakopi.entrypoints: websecure
      traefik.http.routers.petakopi.rule: Host(`petakopi.my`)
      traefik.http.routers.petakopi.tls.certresolver: letsencrypt
  job:
    hosts:
      - petakopi-my-v3
    cmd: bundle exec sidekiq -q default -q mailers

proxy:
  ssl: true
  host: petakopi.my
  forward_headers: true
  healthcheck:
    timeout: 60

registry:
  username: amree
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
    POSTGRES_USER: "postgres"
    POSTGRES_DB: "petakopi"
    POSTGRES_HOST: "petakopi-db"
    REDIS_URL: "redis://petakopi-redis:6379/0"
  secret:
    - APPLE_CLIENT_ID
    - APPLE_TEAM_ID
    - APPLE_KEY_ID
    - APPLE_PRIVATE_KEY
    - BUGSNAG_API_KEY
    - CLOUDFLARE_R2_ACCESS_KEY_ID
    - CLOUDFLARE_R2_ENDPOINT
    - CLOUDFLARE_R2_SECRET_ACCESS_KEY
    - CLOUDFLARE_TURNSTILE_SECRET_KEY
    - CLOUDFLARE_TURNSTILE_SITE_KEY
    - GOOGLE_API_KEY_API
    - GOOGLE_API_KEY_WEB
    - GOOGLE_OAUTH_CLIENT_ID
    - GOOGLE_OAUTH_CLIENT_SECRET
    - GOOGLE_SERVICE_SPREADSHEET_EMAIL
    - GOOGLE_SERVICE_SPREADSHEET_PRIVATE_KEY
    - KAMAL_REGISTRY_PASSWORD
    - MAPBOX_API_KEY
    - NEWRELIC_LICENSE_KEY
    - POSTGRES_PASSWORD
    - RAILS_MASTER_KEY
    - RESEND_API_KEY
    - SECRET_KEY_BASE
    - SKYLIGHT_AUTH_TOKEN
    - TELEGRAM_BOT_TOKEN
    - TELEGRAM_NOTIFICATION_CHAT_ID
    - TINIFY_API_KEY

aliases:
  shell: app exec --interactive --reuse "bash"
  console: app exec --interactive --reuse "bundle exec rails console"
  logs: app logs -f

ssh:
  user: root

accessories:
  db:
    image: postgis/postgis:17-3.5
    host: petakopi-my-v3
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "petakopi"
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2
    host: petakopi-my-v3
    directories:
      - data:/data
